apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
  labels:
    app: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      hostNetwork: true
      containers:
      - name: ping
        image: dpn:latest
        args: ["ping.json"]
        imagePullPolicy: Never